"use client";

import { useActionState, useState } from "react";
import { AppIcon, type AppIconName } from "@/components/app-icon";
import { invitePerson, type InviteState } from "./actions";

type Person = { userId: string; name: string; role: string; status: string; isAccessAdmin: boolean; readAreas: string[]; childId: string };
const initialState: InviteState = {};
const readAreas = ["documents", "evidence", "review", "action"] as const;
const roleIcon = (role: string): AppIconName => role === "senco" || role === "school_staff" ? "register" : role === "professional" ? "caseload" : role === "local_authority" ? "decisions" : "children";
const roleLabel: Record<string, string> = { parent: "Parent", family: "Family", senco: "SENCO", school_staff: "School staff", professional: "Professional", local_authority: "Local Authority" };

export function CircleManager({ people, childOptions }: { people: Person[]; childOptions: { id: string; preferred_name: string }[] }) {
  const [open, setOpen] = useState(false); const [selectedAreas, setSelectedAreas] = useState<string[]>([]); const [state, action, pending] = useActionState(invitePerson, initialState);
  return <><div className="panel-title"><div><p className="eyebrow">AUTHORISED CIRCLE</p><h2>People with access</h2></div><button className="button button--small" type="button" onClick={() => setOpen((value) => !value)}>+ Invite someone</button></div>
    {open && <form className="invite-form" action={action}><label className="field">Child<select name="child_id" required defaultValue=""><option value="" disabled>Choose a child</option>{childOptions.map((child) => <option key={child.id} value={child.id}>{child.preferred_name}</option>)}</select></label><label className="field">Email address<input name="email" type="email" required /></label><label className="field">Role<select name="role" defaultValue=""><option value="" disabled>Choose a role</option><option value="senco">SENCO</option><option value="school_staff">School staff</option><option value="professional">Professional</option><option value="local_authority">Local Authority</option></select></label><fieldset><legend>Record areas</legend><button className="permission-select-all" type="button" onClick={() => setSelectedAreas(selectedAreas.length === readAreas.length ? [] : [...readAreas])}>{selectedAreas.length === readAreas.length ? "Clear all" : "Select all"}</button><div className="permission-options">{readAreas.map((area) => { const label = area === "review" ? "Reviews" : area[0].toUpperCase() + area.slice(1); return <label className="permission-chip" data-selected={selectedAreas.includes(area)} key={area}><input type="checkbox" name="read_areas" value={area} checked={selectedAreas.includes(area)} onChange={(event) => setSelectedAreas((current) => event.target.checked ? [...current, area] : current.filter((value) => value !== area))} /> <span>{label}</span></label>; })}</div><div className="permission-contribute"><span>Additional permissions</span><label className="permission-chip"><input type="checkbox" name="contribute_areas" value="documents" /> <span>Can contribute documents</span></label><label className="permission-chip"><input type="checkbox" name="contribute_areas" value="evidence" /> <span>Can contribute evidence</span></label></div></fieldset><button className="button button--small" type="submit" disabled={pending}>{pending ? "Creating…" : "Create secure invitation"}</button>{state.error && <p className="form-message form-message--error" role="alert">{state.error}</p>}{state.message && <div className="form-message"><p>{state.message}</p><input aria-label="Invitation link" readOnly value={state.invitationUrl} /></div>}</form>}
    <div className="people-list">{people.length ? people.map((person) => <article key={`${person.childId}-${person.userId}`}><span className="person-avatar"><AppIcon name={roleIcon(person.role)} size={22} /></span><div><h3>{person.name}</h3><p>{roleLabel[person.role] ?? person.role}</p></div><div><small>ACCESS</small><strong>{person.isAccessAdmin ? "Circle administrator" : person.readAreas.length ? person.readAreas.join(", ") : "No record areas"}</strong></div><i data-pending={person.status !== "active"}>{person.status}</i></article>) : <p className="empty-filter">No authorised members are available to show.</p>}</div></>;
}
